### ISSUE TITLE
Monster paralyze stays even after removing the debuff

### ISSUE THREAD

**Issue by TobiWigley** [kite1348/overtakeOT_issues#18]
Issue: Paralyze stays even after removing the debuff

Character Vocation: Druid
Location: Port Hope Dworc caves
Monster: Dworc Voodoomaster
Monster spell: Paralysis

Bug Details: 

I first entered the cave without the invisibility spell utana vid, then later on used utana vid to hide myself from the Dworcs meaning the Dworcs could no longer paralyze me.

I used the Utani gran hur spell to remove the paralysis debuff, the haste spell granted me speed as it should, however when the haste buff ends the paralysis effect is still on my character even though the debuff icon for paralysis is not shown. I tried using a healing spell exura gran to see if it removed the bugged paralysis effect but to no avail, you can only use a haste spell to move properly after it bugs.

I left the cave and went to a protection zone to make sure this wasn't a bug with Dworc Voodoomasters targeting and them being able to paralyze targets that they can't see, but I was still paralyzed even standing on port hope's boat inside its protection zone.

Logging out resolved the paralysis bug.

**Comment by kite1348** [comment]
fixed at ss
